$ANSIBLE_VAULT;1.1;AES256
66306361303131616366373030623236393235656538303030396262363739383338383464383430
3537333766653661393630383034616566336164646137640a333434613236636531663563666362
30626365636338393161666165313564393634646162383239646435376438613364633862353530
3961373163633938630a666430646539373465653462323961666430653535313537343134333366
34313935353164393236626337663737366436303839323838336362343664346635356661613136
3365626536323462666263313666353439653436373731393232
