---
- name: Gather information
  hosts: all
  tasks: []
- name: generate myhost file with template 
  hosts: all
  tasks:
    - name: create myhost file
      template:
        src: ../templates/myhosts.j2
        dest: /etc/myhosts
      