--- 

- name: Gather hardware information
  hosts: all
  tasks: []
- name: Create hardware report file
  hosts: localhost
  tasks:
    - name: Create hardware report file
      template:
        src: ../templates/hwreport.j2
        dest: /root/hwreport.txt
