--- 

- name: test playbook
  hosts: test
  tasks:
    - name: create /webtest directory
      file:
        path: /webtest
        state: directory
        mode: '2755'
    
    - name: install httpd package
      package:
        name: httpd
        state: present

    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true 
    
    - name: write content to index.html 
      copy:
        dest: /webtest/index.html
        content: "Testing"
        mode: '0644'
     
    - name: create /var/www/html/webtest
      file:
        path: /var/www/html/webtest
        state: directory

    - name: create symoblic link to index.html
      file:
        src: /webtest/index.html
        dest: /var/www/html/webtest/index.html
        state: link            