---

- name: configure repositories
  hosts: all
  tasks:

    - name: configure BaseOS
      yum_repository:
        name: BaseOS
        baseurl: file:///mnt/BaseOS/
        description: 'Base OS Repo'
        gpgcheck: no
        enabled: yes
        # key: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

    - name: configure AppStream
      yum_repository:
        name: AppStream
        baseurl: file:///mnt/AppStream/
        description: 'AppStream Repo'
        gpgcheck: no
        enabled: yes
        # key: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    
    - name: Install cowsay package
      yum:
        name: cowsay
        state: present
    - name: Check cowsay package
      command: "rpm -qa cowsay"